[package]
name = "sharp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
pretty_env_logger = "0.4.0"

tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros", "net"] }
axum = { version = "0.6.12" }
hyper = { version = "0.14.25", features = ["client"] }
tower = { version = "0.4.13", features = ["make"] }
