name: Rust

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose

    lints:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Clippy
              run: cargo clippy -- -Dwarnings
            - name: Rustfmt
              run: cargo +nightly fmt --check
